name: Generate Docs

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  changes:
    runs-on: ubuntu-latest
    if: github.repository == 'greatsquare0/thy-weaver'

    outputs:
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if docs folder changed
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs:
              - "packages/docs/**"

  generate-docs:
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: changes
    if: ${{steps.filter.outputs.docs == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depht: 0

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm turbo run @thy-weaver/docs#dev

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/docs/dist

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: generate-docs
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
